### ISSUE TITLE
Bug: No commit actvity

### ISSUE THREAD

**Issue by MarcMouallem** [omarshammas/jquery.formance#29]
I would like to use this library but, I have noticed there has not been a commit in over two years. Please fix this bug or let us know if it's a no fix.

**Comment by omarshammas** [comment]
Marc, you're are 100% correct.

I do not have any time to support this project now and will update the Read Me accordingly. I don't want people incorporating unsupported libraries in their new projects.

If you'd like to continue you work on the project, please fork it. You can find the next release I was working on a while back here on the `revamp` branch. https://github.com/omarshammas/jquery.formance/tree/revamp

Best of luck.

**Comment by MarcMouallem** [comment]
Thanks for getting back to me! I was just kidding around by the way.
